apiVersion: v1
kind: ConfigMap
metadata:
  name: pulsecraft-config
  namespace: pulsecraft
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8080"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"
