apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pulsecraft-ingress
  namespace: pulsecraft
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "16m"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  tls:
    - hosts:
        - harsavardhandevops.online
        - www.harsavardhandevops.online
      secretName: pulsecraft-tls-secret
  rules:
    - host: harsavardhandevops.online
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: pulsecraft-backend-service
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pulsecraft-frontend-service
                port:
                  number: 80
    - host: www.harsavardhandevops.online
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: pulsecraft-backend-service
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pulsecraft-frontend-service
                port:
                  number: 80
