apiVersion: v1
kind: Secret
metadata:
  name: pulsecraft-secret
  namespace: pulsecraft
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "sa"
  SPRING_DATASOURCE_PASSWORD: "pulsecraft_secure_password_2026"
